version: '3'

networks:
  scc311coursework:

services:
  server:
    container_name: server
    image: harbor.scc.lancs.ac.uk/hardys/server:latest
    restart: unless-stopped
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    build:
      context: ./server/
    networks:
      - scc311coursework
    ports:
      - 8080:8080

  load-balancer:
    container_name: load-balancer
    image: harbor.scc.lancs.ac.uk/hardys/load-balancer:latest
    restart: unless-stopped
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    build:
      context: load-balancer
    networks:
      - scc311coursework
    ports:
      - 9090:8080

  redis:
    container_name: redis
    image: redis:5.0.6
    restart: unless-stopped
    networks:
      - scc311coursework
    ports:
      - 6379:6379
